### ISSUE TITLE
可否对db文件中的字段进行解释？

### ISSUE THREAD

**Issue by FishZe** [chinosk114514/chachengfen#1]
我已经制作好了3个账号，计划插入db文件中
但是db文件中的字段我不明白是什么含义，可否进行解释？

**Comment by chinosk6** [comment]
- `uid`字段应该不需要解释
 - `full_cookie`是你的完整cookie, 浏览器F12可以直接看到
 - `SESSDATA`和`bili_jct`是cookie中的两个字段, 直接复制出来即可
 - `following_count`是这个账号正在关注的数量

**Comment by FishZe** [comment]
1. 该api已经对开启隐私设置的用户失去作用，会导致部分用户查询失败
2. 由于api接口`code`字段的改变，程序没有特判，设置隐私的用户会导致报错。

我大致修改了几行代码，如果有需要我可以pr一下，但是比较少，没有太多必要（）。

**Comment by chinosk6** [comment]
可以pr当然是最好的, 我也懒得去看新code了(
