### ISSUE TITLE
请问为何要在此处加Proxy？

### ISSUE THREAD

**Issue by LxnChan** [chinosk114514/chachengfen#4]
![image](https://user-images.githubusercontent.com/46388610/189607204-a5fb9446-c7bd-450a-82bb-bf982570756d.png)

目前我这测试是不能使用的，注释掉Proxy也会报别的错误。

**Comment by chinosk6** [comment]
因为国内网络环境访问该api速度不是很理想。不需要proxy注释掉即可。"别的错误"是什么错误

**Comment by LxnChan** [comment]
没有问题了233
